# Generated by Django 5.0.6 on 2024-06-28 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_cancha', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField()),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_por_fecha', to='AppReserva.cancha')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_por_hora', to='AppReserva.cancha')),
                ('numero_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_por_cancha', to='AppReserva.cancha')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.BooleanField()),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_fecha', to='AppReserva.cancha')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_hora', to='AppReserva.cancha')),
                ('numero_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_cancha', to='AppReserva.cancha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.TimeField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_reserva', to='AppReserva.reserva')),
            ],
        ),
    ]
