# Generated by Django 5.0.6 on 2024-07-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReserva', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearUsuario',
            new_name='Register',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
